Test_Groups = {
    "NMR Lipoporotein Profili" : {
        "Trigliserid": {"Birim": "mg/dL" , "Referans Değer": {"Optimal Düzey": ["<",150],
                                                              "Artmış Kardiovasküler Hastalık Riski":[">",150]}},
        "Kolestrol, total": {"Birim": "mg/dL", "Referans Değer": {"Optimal Düzey": ["<",200],
                                                              "Artmış Kardiovasküler Hastalık Riski":[">",200]}},
        "Kolestrol, LDL": {"Birim": "mg/dL", "Referans Değer": {"Kardiyovasküler Hastalığı Olanlarda Optimal Düzey": ["<",70],
                                                                "Kardiyovasküler Hastalığı Olmayanlarda Optimal Düzey": ["<",100],
                                                              "Artmış Kardiovasküler Hastalık Riski":[">",130]}},
        "Kolestrol, HDL": {"Birim": "mg/dL", "Referans Değer": {"Optimal Düzey": ["<",50],
                                                              "Artmış Kardiovasküler Hastalık Riski":[">",50]} },
        "Kolestrol, LDL/ Kolestrol, HDL Oranı": {"Birim": "mg/dL", "Referans Değer": {"Optimal Düzey": ["<",2],
                                                              "Artmış Kardiovasküler Hastalık Riski":[">",5]}},
        "Apolipoprotein A1": {"Birim": "mg/dL" , "Referans Değer": None},
        "Apolipoprotein A2": {"Birim": "mg/dL" , "Referans Değer": None},
        "Apolipoprotein B100": {"Birim": "nmol/L" , "Referans Değer": None},
        "Apo-B100 / Apo-A1 Oranı": {"Birim": "nmol/L", "Referans Değer": {"Optimal Düzey": ["<",0.6],
                                                              "Artmış Kardiovasküler Hastalık Riski":[">",0.8]}},
        "Total ApoB Taşıyan Partikül Sayısı, Total ApoB-P": {"Birim": "nmol/L", "Referans Değer": {"Optimal Düzey": ["<",1400],
                                                              "Artmış Kardiovasküler Hastalık Riski":[">",2000]}},
        "LDL Partikül Sayısı, LDL-P": {"Birim": "nmol/L" , "Referans Değer": {"Optimal Düzey": ["<",1000],
                                                              "Artmış Kardiovasküler Hastalık Riski":[">",1300]}},
        "IDL Partikül Sayısı, IDL-P": {"Birim": "nmol/L", "Referans Değer": {"Optimal Düzey": ["<",70],
                                                              "Artmış Kardiovasküler Hastalık Riski":[">",100]}},
        "VLDL Partikül Sayısı, VLDL-P": {"Birim": "nmol/L", "Referans Değer": {"Optimal Düzey": ["<",120],
                                                              "Artmış Kardiovasküler Hastalık Riski":[">",180]}}

    } ,
    "LDL ALT FRAKSİYONLARI": {
        "LDL1-Partikül Sayısı": {"Birim": "nmol/L" , "Referans Değer": {"Optimal Düzey": ["<",140],
                                                              "Artmış Kardiovasküler Hastalık Riski":[">",190]}},
        "LDL2-Partikül Sayısı": {"Birim": "nmol/L" , "Referans Değer": {"Optimal Düzey": ["<",150],
                                                              "Artmış Kardiovasküler Hastalık Riski":[">",200]}},
        "LDL3-Partikül Sayısı": {"Birim": "nmol/L" , "Referans Değer": {"Optimal Düzey": ["<",190],
                                                              "Artmış Kardiovasküler Hastalık Riski":[">",260]}},
        "LDL4-Partikül Sayısı": {"Birim": "nmol/L" , "Referans Değer": {"Optimal Düzey": ["<",230],
                                                              "Artmış Kardiovasküler Hastalık Riski":[">",330]}},
        "LDL5-Partikül Sayısı": {"Birim": "nmol/L" , "Referans Değer": {"Optimal Düzey": ["<",290],
                                                              "Artmış Kardiovasküler Hastalık Riski":[">",400]}},
        "LDL6-Partikül Sayısı": {"Birim": "nmol/L" , "Referans Değer": {"Optimal Düzey": ["<",300],
                                                              "Artmış Kardiovasküler Hastalık Riski":[">",450]}},
    } ,
    "ATEROJENİK LİPOPROTEİNLERDE APO-B100 VE TRİGLİSERİD" : {
        "LDL-Apo-B100": {"Birim": "mg/dL" , "Referans Değer": {"Optimal Düzey": ["<",70],
                                                              "Artmış Kardiovasküler Hastalık Riski":[">",100]}},
        "IDL-Apo-B100": {"Birim": "mg/dL" , "Referans Değer": {"Optimal Düzey": ["<",4],
                                                              "Artmış Kardiovasküler Hastalık Riski":[">",6]}},
        "VLDL-Apo-B100": {"Birim": "mg/dL" , "Referans Değer": {"Optimal Düzey": ["<",6],
                                                              "Artmış Kardiovasküler Hastalık Riski":[">",10]}},
        "LDL-Trigliserid": {"Birim": "mg/dL" , "Referans Değer": {"Optimal Düzey": ["<",24],
                                                              "Artmış Kardiovasküler Hastalık Riski":[">",28]}},
        "IDL-Trigliserid": {"Birim": "mg/dL" , "Referans Değer": {"Optimal Düzey": ["<",6],
                                                              "Artmış Kardiovasküler Hastalık Riski":[">",10]}},
        "VLDL-Trigliserid": {"Birim": "mg/dL" , "Referans Değer": {"Optimal Düzey": ["<",60],
                                                              "Artmış Kardiovasküler Hastalık Riski":[">",90]}},

    },
    "LİPOPROTEİN KOLESTROL ESTERİFİKASYONU" : {
        "LDL Serbest Kolestrol": {"Birim": None , "Referans Değer": None },
        "HDL Serbest Kolestrol": {"Birim": None , "Referans Değer": None },
        "LDL-Serbest Kolestrol / LDL-Kolestrol": {"Birim": None , "Referans Değer": {"Optimal Düzey": ["<",0.5],
                                                              "Artmış Kardiovasküler Hastalık Riski":[">=",0.5]}},
        "HDL-Serbest Kolestrol / HDL-Kolestrol": {"Birim": None , "Referans Değer": {"Optimal Düzey": ["<",0.5],
                                                              "Artmış Kardiovasküler Hastalık Riski":[">=",0.5]}},

    }
}